apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-routing
spec:
  gateways:
  - jenkins-gateway
  hosts:
  - "jenkins.{{ .Values.global.domain }}"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-jenkins
        port:
          number: {{ .Values.jenkins.service.port }}
